trapper/apps/media_classification/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url, include
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

from rest_framework.routers import DefaultRouter
from rest_framework.urlpatterns import format_suffix_patterns

from trapper.apps.media_classification.views import (
    api as classification_api_views
)
from trapper.apps.media_classification.views import (
    classifications as classifications_views,
    user_classifications as user_classifications_views,
    projects as projects_views,
    classificators as classificators_views,
    sequences as sequences_views 
)


router = DefaultRouter(trailing_slash=False)

router.register(
    r'classificators',
    classification_api_views.ClassificatorViewSet,
    base_name='api-classificator'
)

router.register(
    r'user-classifications',
    classification_api_views.UserClassificationViewSet,
    base_name='api-user-classification'
)

router.register(
    r'classifications',
    classification_api_views.ClassificationViewSet,
    base_name='api-classification'
)

router.register(
    r'classifications_map',
    classification_api_views.ClassificationMapViewSet,
    base_name='api-classification-map'
)

router.register(
    r'classification-projects',
    classification_api_views.ClassificationProjectViewSet,
    base_name='api-classification-project'
)

router.register(
    r'classification-project-collections',
    classification_api_views.ClassificationProjectCollectionViewSet,
    base_name='api-classification-project-collection'
)

router.register(
    r'sequences',
    classification_api_views.SequenceViewSet,
    base_name='api-sequence'
)

router.register(
    r'classification/(?P<collection_pk>\d+)/(?P<current_resource_pk>\d+)/resources/$',
    classification_api_views.ClassificationResourcesViewSet,
    base_name='api-classification-resources'
)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(
        r'^api/classifications/results/(?P<project_pk>\d+)/',
        classification_api_views.ClassificationResultsView.as_view(),
        name='api-classification-results'
    ),
    url(
        r'^api/classifications/import',
        classification_api_views.ClassificationImport.as_view(),
        name='api-classification-import'
    )
]

urlpatterns += [

    url(
        r'^$',
        RedirectView.as_view(
            url=reverse_lazy('media_classification:project_list')
        ),
        name='project_index'
    ),

    # Project views
    url(
        r'project/list/$',
        projects_views.view_project_list, 
        name='project_list'
    ),
    url(
        r'project/detail/(?P<pk>\d+)/$',
        projects_views.view_project_detail,
        name='project_detail'
    ),

    url(
        r'project/create/$', 
        projects_views.view_project_create,
        name='project_create'
    ),
    url(
        r'project/update/(?P<pk>\d+)/$', 
        projects_views.view_project_update,
        name='project_update'
    ),
    url(
        r'project/delete/(?P<pk>\d+)/$',
        projects_views.view_project_delete,
        name='project_delete'
    ),
    url(
        r'^project/delete/$',
        projects_views.view_project_delete,
        name='project_delete_multiple'
    ),
    url(
        r'project/collection/add/$',
        projects_views.view_project_collection_add,
        name='project_collection_add'
    ),
    url(
        r'project/collection/delete/(?P<pk>\d+)/$',
        projects_views.view_project_collection_delete,
        name='project_collection_delete'
    ),
    url(
        r'^project/collection/delete/$',
        projects_views.view_project_collection_delete,
        name='project_collection_delete_multiple'
    ),

    url(
        (
            r'project/(?P<name>(sequence|crowdsourcing))/'
            r'(?P<action>(activate|deactivate))/$'
        ),
        projects_views.view_project_action,
        name="project_action"
    ),
    url(
        r'project/action/(?P<name>(status))/(?P<action>(ongoing|finished))/$',
        projects_views.view_project_action,
        name="project_action"
    ),

    # Classificator views
    url(
        r'classificator/list/$', 
        classificators_views.view_classificator_list,
        name='classificator_list'
    ),
    url(
        r'classificator/detail/(?P<pk>\d+)/$',
        classificators_views.view_classificator_detail, 
        name='classificator_detail'
    ),

    url(
        r'classificator/create/$', 
        classificators_views.view_classificator_create,
        name='classificator_create'
    ),
    url(
        r'classificator/update/(?P<pk>\d+)/$',
        classificators_views.view_classificator_update,
        name='classificator_update'
    ),
    url(
        r'classificator/clone/(?P<pk>\d+)/$',
        classificators_views.view_classificator_clone,
        name='classificator_clone'
    ),
    url(
        r'^classificator/delete/(?P<pk>\d+)/$',
        classificators_views.view_classificator_delete,
        name='classificator_delete'
    ),
    url(
        r'^classificator/delete/$',
        classificators_views.view_classificator_delete,
        name='classificator_delete_multiple'
    ),

    # Sequence views
    url(
        r'sequence/create/$',
        sequences_views.view_sequence_change,
        name='sequence_create'
    ),
    url(
        r'sequence/update/$',
        sequences_views.view_sequence_change,
        name='sequence_update'
    ),
    url(
        r'sequence/change/$',
        sequences_views.view_sequence_change,
        name='sequence_change'
    ),
    url(
        r'sequence/delete/$',
        sequences_views.view_sequence_delete,
        name='sequence_delete'
    ),
    url(
        r'^sequence/build/$',
        sequences_views.view_sequence_build,
        name='sequence_build'
    ),

    # Classification views
    url(
        r'classification/detail/(?P<pk>\d+)/$',
        classifications_views.view_classification_detail,
        name='classification_detail'
    ),
    url(
        r'^classification/list/(?P<pk>\d+)/$',
        classifications_views.view_classification_list,
        name='classification_list'
    ),
    url(
        r'classification/import/$',
        classifications_views.view_classification_import,
        name='classification_import'
    ),
    url(
        r'classification/import/(?P<pk>\d+)/$',
        classifications_views.view_classification_import,
        name='classification_import'
    ),
    url(
        r'classification/export/(?P<pk>\d+)/$',
        classifications_views.view_classification_export,
        name='classification_export'
    ),
    url(
        r'classification/form/(?P<pk>\d+)/$',
        classifications_views.view_classification_tag,
        name='classification_tag'
    ),
    url(
        r'classification/delete/(?P<pk>\d+)/$',
        classifications_views.view_classification_delete,
        name='classification_delete'
    ),
    url(
        r'classification/delete/$',
        classifications_views.view_classification_delete,
        name='classification_delete_multiple'
    ),
    url(
        r'classify/(?P<project_pk>\d+)/(?P<collection_pk>\d+)/$',
        classifications_views.view_classify_collection,
        name='classify_collection'
    ),
    url(
        r'classify/(?P<pk>\d+)/$',
        classifications_views.view_classify_resource,
        name='classify'
    ),
    url(
        r'classify/(?P<pk>\d+)/user/(?P<user_pk>\d+)/$',
        classifications_views.view_classify_resource,
        name='classify_user'
    ),
    url(
        r'classify/approve/(?P<pk>\d+)/$',
        classifications_views.view_classify_approve,
        name='classify_approve'
    ),

    # UserClassification views
    url(
        r'user_classification/list/(?P<pk>\d+)/$',
        user_classifications_views.view_user_classification_list,
        name='user_classification_list'
    ),
    url(
        r'user_classification/approve/(?P<pk>\d+)/$',
        user_classifications_views.view_user_classification_bulk_approve,
        name='user_classification_bulk_approve'
    )

]

trapper/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.gis import admin as admin_gis
from django.conf import settings
from django.conf.urls.static import static
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from trapper.apps.accounts.views import accounts as accounts_views

admin.autodiscover()

urlpatterns = [
    # Overrides
    # Overwrite account inactive url provided by django-allauth so user
    # is redirected to homepage instead of templateless inactive user
    url(
        r'^account/inactive/$',
        RedirectView.as_view(url=reverse_lazy('trapper_index')),
        name='account_inactive'
    ),
    # Trapper homepage
    url(
        r'^$',
        accounts_views.view_index,
        name='trapper_index'
    ),
    # Media classification urls
    url(
        r'^media_classification/',
        include(
            'trapper.apps.media_classification.urls',
            namespace='media_classification'
        )
    ),
    # Research urls
    url(
        r'^research/',
        include(
            'trapper.apps.research.urls',
            namespace='research'
        )
    ),
    # Storage urls
    url(
        r'^storage/',
        include(
            'trapper.apps.storage.urls',
            namespace='storage'
        )
    ),
    # Messaging urls
    url(
        r'^messaging/',
        include(
            'trapper.apps.messaging.urls',
            namespace='messaging'
        )
    ),
    # Accounts urls
    url(
        '',
        include('django.contrib.auth.urls')
    ),
    url(
        r'^accounts/',
        include(
            'trapper.apps.accounts.urls',
            namespace='accounts'
        )
    ),
    url(
        r'^account/',
        include('allauth.urls')
    ),
    # GeoMap urls
    url(
        r'^geomap/',
        include(
            'trapper.apps.geomap.urls',
            namespace='geomap'
        )
    ),
    # Comments
    url(
        r'^comments/',
        include(
            'trapper.apps.comments.urls',
            namespace='comments'
        )
    ),
    # Sendfile urls
    url(
        r'^serve/',
        include(
            'trapper.apps.sendfile.urls',
            namespace='sendfile'
        )
    ),
    # Forum
    url(
        r'^forum/',
        include(
            'djangobb_forum.urls',
            namespace='djangobb'
        )
    ),

    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin_gis/', include(admin_gis.site.urls)),
    url(r'', include('leaflet_storage.urls')),
    # REST API Swagger docs
    url(r'^docs/api/', include('rest_framework_swagger.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = urlpatterns + [
        url(
            r'^__debug__/', 
            include(debug_toolbar.urls)
        )
    ] + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    ) + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

trapper/apps/media_classification/templates/media_classification/classificators/detail.html
{% extends "media_classification/index.html" %}

{% block section_content %}
<div class="container">
  <h2>Clasificator name: <strong>{{ classificator.name }}</strong>
    <form class="pull-right" action="{% url 'media_classification:classificator_clone' pk=classificator.pk %}" method='post'>
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Copy this classificator</button>
    </form>
  </h2>
  <div class="panel panel-default">

    <div class="panel-heading">
      <h2 class="panel-title">Dynamic form attributes</h2>
    </div>
    <div class="panel-body">
      <table class="table table-striped table-rich" id="id_dynamic_attrs">
        {% if attributes_dynamic %}
        <thead>
          <tr>
          <th>Name</th>
          <th>Type</th>
          <th>HStore</th>
          </tr>
        </thead>
        <tbody>
          {% for params in attributes_dynamic %}
          <tr>
            <td>{{ params.name }}</td>
            <td><span class="label {{ params.cls }}">{{ params.type }}</span></td>
            <td>{% if params.is_custom %}
              <pre>{{ params.hstore }}</pre>{% endif %}</td>
          </tr>
          {% endfor %}
        </tbody>
        {% else %}
        <tbody>
          <tr>
            <td colspan="5" class="alert alert-warning ng-binding"><span class="fa fa-info"></span> There are no dynamic
              attributes defined.
            </td>
          </tr>
        </tbody>
        {% endif %}
      </table>
    </div>

    <div class="panel-heading">
      <h2 class="panel-title">Static form attributes</h2>
    </div>
    <div class="panel-body">
      <table class="table table-striped table-rich" id="id_static_attrs">
        {% if attributes_static %}
        <thead>
          <tr>
            <th>Name</th>
            <th>Type</th>
            <th>HStore</th>
          </tr>
        </thead>
        <tbody>
          {% for params in attributes_static %}
          <tr>
            <td>{{ params.name }}</td>
            <td><span class="label {{ params.cls }}">{{ params.type }}</span></td>
            <td>{% if params.is_custom %}
              <pre>{{ params.hstore }}</pre>{% endif %}</td>
          </tr>
          {% endfor %}
        </tbody>
        {% else %}
        <tbody>
          <tr>
            <td colspan="5" class="alert alert-warning ng-binding"><span class="fa fa-info"></span> There are no static
              attributes defined.
            </td>
          </tr>
        </tbody>
        {% endif %}
      </table>
    </div>

  </div>
</div>

{% endblock section_content %}

trapper/apps/media_classification/templates/media_classification/classificators/form.html
{% extends 'media_classification/index.html' %}

{% load crispy_forms_tags %}

{% block data_app %}classificator::create{% endblock data_app %}

{% block section_content %}

    <div class="container">
        <form class="panel panel-default" action="" name="attr-form" method="post">
            <div class="panel-heading">
                <h2 class="panel-title">{% if classificator %}Update{% else %}Add{% endif %} classificator</h2>
            </div>

            <div class="row panel-body">

                <div class="col-md-12 form-group form-required">
                    {% crispy classificator_form classificator_form.helper %}
                </div>

                <div class="col-md-8">
                    {% include 'media_classification/classificators/form_left.html' %}
                </div>

                <div class="col-md-4">
                    {% include 'media_classification/classificators/form_right.html' %}
                </div>
            </div>

            <div class="panel-footer">
                <button type="submit" name="submit" value="change" class="btn btn-success">Add/Update classificator
                </button>
            </div>
        </form>
    </div>
{% endblock section_content %}

trapper/apps/media_classification/templates/media_classification/classificators/form_left.html
{% load crispy_forms_tags %}

<h3>Dynamic form attributes</h3>

<table class="table table-striped table-rich" id="id_dynamic_attrs">
    {% if attributes_dynamic %}
        <thead>
        <tr>
            <th>Name</th>
            <th>Type</th>
            <th>HStore</th>
            <th>Actions</th>
            <th>Order</th>
        </tr>
        </thead>

        <tbody>
        {% for params in attributes_dynamic %}
            <tr>
                <td>{{ params.name }}</td>
                <td><span class="label {{ params.cls }}">{{ params.type }}</span></td>
                <td>{% if params.is_custom %}
                    <pre>{{ params.hstore }}</pre>{% endif %}</td>
                <td>
                    {% if params.is_custom %}
                        <button type="submit" name="updateAttr" value="{{ params.name }}"
                                class="btn btn-default btn-xs"><span class="fa fa-pencil"></span></button>
                        <button type="submit" name="removeAttr" value="{{ params.name }}" class="btn btn-danger btn-xs">
                            <span class="fa fa-remove"></span></button>
                    {% endif %}
                </td>
                <td>
                    <button type="button" class="btn btn-default btn-xs" data-move="-1"><span
                            class="fa fa-arrow-up"></span></button>
                    <button type="button" class="btn btn-default btn-xs" data-move="1"><span
                            class="fa fa-arrow-down"></span></button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    {% else %}
        <tbody>
        <tr>
            <td colspan="5" class="alert alert-warning ng-binding"><span class="fa fa-info"></span> There are no dynamic
                attributes defined.
            </td>
        </tr>
        </tbody>
    {% endif %}
</table>


<h3>Static form attributes</h3>

<input type="hidden" id="static-attrs-order" name="id_static_attrs_order">

<table class="table table-striped table-rich" id="id_static_attrs">
    {% if attributes_static %}
        <thead>
        <tr>
            <th>Name</th>
            <th>Type</th>
            <th>HStore</th>
            <th>Actions</th>
            <th>Order</th>
        </tr>
        </thead>

        <tbody>
        {% for params in attributes_static %}
            <tr>
                <td>{{ params.name }}</td>
                <td><span class="label {{ params.cls }}">{{ params.type }}</span></td>
                <td>{% if params.is_custom %}
                    <pre>{{ params.hstore }}</pre>{% endif %}</td>
                <td>
                    {% if params.is_custom %}
                        <button type="submit" name="updateAttr" value="{{ params.name }}"
                                class="btn btn-default btn-xs"><span class="fa fa-pencil"></span></button>
                        <button type="submit" name="removeAttr" value="{{ params.name }}" class="btn btn-danger btn-xs">
                            <span class="fa fa-remove"></span></button>
                    {% endif %}
                </td>
                <td>
                    <button type="button" class="btn btn-default btn-xs" data-move="-1"><span
                            class="fa fa-arrow-up"></span></button>
                    <button type="button" class="btn btn-default btn-xs" data-move="1"><span
                            class="fa fa-arrow-down"></span></button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    {% else %}
        <tbody>
        <tr>
            <td colspan="5" class="alert alert-warning ng-binding"><span class="fa fa-info"></span> There are no static
                attributes defined.
            </td>
        </tr>
        </tbody>
    {% endif %}
</table>

trapper/apps/media_classification/templates/media_classification/classificators/form_right.html
{% load crispy_forms_tags %}


<h3 class="collapsable active">Define custom attribute</h3>

<div>
    {% crispy custom_form custom_form.helper %}
    <button type="submit" class="btn btn-success" name="custom_attrs_manage">Add / Update</button>
    <button type="button" class="btn btn-default" data-clear>Clear</button>
</div>

<h3 class="collapsable">Choose pre-defined attribute</h3>
<ul class="panel-list">
    {% crispy predefined_form predefined_form.helper %}
</ul>

trapper/apps/media_classification/templates/media_classification/classificators/grid.html
{% extends "common/grid.html" %}

{% block filters %}

<div class="form-group form-filter form-datepicker">
  <label class="control-label">Updated</label>
  <div class="input-group input-daterange"
       filter-daterange="filters.udate"
       filter-name="'udate'"
       filter-service="filter">
    <input
       type="text"
       class="form-control"
       placeholder="from"
       >
    <span class="input-group-addon">
      <span class="fa fa-calendar"></span>
    </span>
    
    <input
       type="text"
       class="form-control"
       placeholder="to"
       >
  </div>
</div>

<div class="form-group form-filter-full">
  <label for="owners" class="control-label">Owners</label>
  <select
     type="text"
     id="owners"
     class="select2-default"
     multiple
     ng-model="filters.owners"
     filter-tokens="owner"
     filter-service="filter">
    {% for owner in grid_context.owners %}
    <option value="{{ owner.pk }}">{{ owner|pretty_username }}</option>
    {% endfor %}
  </select>
</div>

{% endblock %}

{% block custom_actions %}
{% endblock%}

{% block custom_actions_list %}

<li ng-class="{'disabled': !filters.owner}">
  <action-remove-selected
   ng-click="execute($event, '{% url "media_classification:classificator_delete_multiple" %}')">
  </action-remove-selected>
</li>

{% endblock%}

{% block table_cells %}

<td data-title="'Name'" sortable="'name'">{[{ record.name }]}</td>
<td data-title="'Owner'" sortable="'owner'"><a ng-href="{[{ record.owner_profile }]}">{[{ record.owner
    }]}</a></td>
<td data-title="'Date updated'" sortable="'updated_date'">{[{ record.updated_date | date:
  dateFormat.table }]}</td>

{% endblock %}

{% block table_cells_extra_actions %}
{% endblock %}

trapper/apps/media_classification/templates/media_classification/classificators/list.html
{% extends "media_classification/index.html" %}

{% load common_tags %}

{% block ng_app %}ng-app="trapperGrid"{% endblock ng_app %}

{% block section_content %}
    {% with grid_context=classificator_context %}
    {% include 'media_classification/classificators/grid.html' %}
    {% endwith %}
{% endblock section_content %}