trapper/apps/accounts/urls.py
# -*- coding: utf-8 -*-
"""
Urls related to users management
"""
from django.conf.urls import url, include

from rest_framework.routers import DefaultRouter

from trapper.apps.accounts.views import api as api_views
from trapper.apps.accounts.views import accounts as accounts_views


router = DefaultRouter(trailing_slash=False)
router.register(
    r'users', api_views.UserViewSet, base_name='api-user'
)

urlpatterns = [

    url(r'^api/', include(router.urls)),
    url(
        r'^profile/$',
        accounts_views.view_mine_profile,
        name='mine_profile'
    ),
    url(
        r'^profile/(?P<username>[\w_\.\+\-]+)/$',
        accounts_views.view_user_profile,
        name='show_profile'
    ),
    url(
        r'^dashboard/$',
        accounts_views.view_dashbord,
        name='dashboard'
    ),
    url(
        r'^celery/cancel/$',
        accounts_views.view_celery_task_cancel,
        name='celery_task_cancel'
    ),
    url(
        r'^data-package/delete/(?P<pk>\d+)/$',
        accounts_views.view_data_package_delete,
        name='data_package_delete'
    ),
    url(
        r'^data-package/(?P<pk>\d+)/$',
        accounts_views.view_data_package_sendfile_media,
        name='data_package_sendfile_media'
    ),
]

trapper/apps/comments/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from trapper.apps.comments import views as comments_views


urlpatterns = [

    url(
        r'^create/$',
        comments_views.view_comment_create,
        name='comment_create'
    ),
    url(
        r'^delete/(?P<pk>\d+)/$',
        comments_views.view_comment_delete,
        name='comment_delete'
    ),
]

trapper/apps/geomap/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.core.urlresolvers import reverse_lazy
from django.views.generic import TemplateView, RedirectView
from django.views.decorators.cache import never_cache

from leaflet_storage.utils import decorated_patterns
from leaflet_storage.decorators import map_permissions_check
from leaflet_storage import views as ls_views

from rest_framework.routers import DefaultRouter

from trapper.apps.geomap.views import api as api_views
from trapper.apps.geomap.views import map as map_views
from trapper.apps.geomap.views import location as location_views
from trapper.apps.geomap.views import deployment as deployment_views


router = DefaultRouter(trailing_slash=False)
router.register(
    r'locations',
    api_views.LocationViewSet,
    base_name='api-location'
)

router.register(
    r'deployments',
    api_views.DeploymentViewSet,
    base_name='api-deployment'
)

router.register(
    r'maps',
    api_views.MapViewSet,
    base_name='api-map'
)

urlpatterns = [
    url(
        r'^api/locations/export/$',
        api_views.LocationTableView.as_view(),
        name='api-location-export'
    ),
    url(
        r'^api/deployments/export/$',
        api_views.DeploymentTableView.as_view(),
        name='api-deployment-export'
    ),
    url(
        r'^api/locations/geojson/$',
        api_views.LocationGeoViewSet.as_view(),
        name='api-location-geojson'
    ),
    url(r'^api/', include(router.urls))
]

urlpatterns += [

    url(
        r'^location/bulk-update/$',
        location_views.view_location_bulk_update,
        name='location_bulk_update'
    ),
    url(
        r'^location/create/$',
        RedirectView.as_view(url=u'/geomap/map/?action=create'),
        name='location_create'
        ),
    url(
        r'^location/(?P<pk>\d+)/delete/$',
        location_views.view_location_delete,
        name='location_delete'
    ),
    url(
        r'^location/delete/$',
        location_views.view_location_delete,
        name='location_delete_multiple'
    ),
    url(r'^location/list/$',
        location_views.view_location_list,
        name='location_list'
    ),
    url(
        r'^location/import/$',
        location_views.view_location_import,
        name='location_import'
    ),
    url(
        r'^location/filterform/$',
        location_views.view_location_filter_form,
        name="locations_filterform"
    ),
    url(
        r'^location/createform/$',
        location_views.view_location_create_form,
        name="locations_createform"
    ),
    url(
        r'^location/(?P<pk>\d+)/editform/$',
        location_views.view_location_edit_filter_form,
        name="locations_editform"
    ),
    url(
        r'^location/collections/$',
        location_views.view_location_collections,
        name="location_collections"
    ),
]

urlpatterns += [

    url(
        r'^map/permissions/update/(?P<map_id>[\d]+)/$',
        map_views.view_update_map_permissions,
        name="map_permissions"
    ),
    url(
        r'^map/(?P<slug>[-_\w]+)_(?P<pk>\d+)$',
        map_views.view_map, 
        name='map'
    ),
    url(
        r'^map/list/$', 
        map_views.view_map_list, 
        name="map_list"),
    url(
        r'^map/(?P<pk>\d+)/delete/$',
        map_views.view_map_delete,
        name='map_delete'
    ),
    url(
        r'^map/delete/$',
        map_views.view_map_delete,
        name='map_delete_multiple'
    ),
    url(
        r'^map/$', 
        map_views.view_new_map, 
        name='map_view'
    ),
    url(
        r'permissions/update/(?P<map_id>\d+)/$',
        map_views.view_update_map_permissions,
        name='map_permissions'
    ),
    url(
        r'^map/create/$', 
        map_views.view_map_create, 
        name='map_create'
    ),
]

urlpatterns += [
    url(r'^map/(?P<map_id>[\d]+)/update/settings/$',
        ls_views.MapUpdate.as_view(), name='map_update'),
    url(r'^map/(?P<map_id>[\d]+)/update/permissions/$',
        ls_views.UpdateMapPermissions.as_view(),
        name='map_update_permissions'),
    url(r'^map/(?P<map_id>[\d]+)/update/delete/$',
        ls_views.MapDelete.as_view(), name='map_delete'),
    url(r'^map/(?P<map_id>[\d]+)/update/clone/$',
        ls_views.MapClone.as_view(), name='map_clone'),
    url(r'^map/(?P<map_id>[\d]+)/datalayer/create/$',
        ls_views.DataLayerCreate.as_view(), name='datalayer_create'),
    url(r'^map/(?P<map_id>[\d]+)/datalayer/update/(?P<pk>\d+)/$',
        ls_views.DataLayerUpdate.as_view(), name='datalayer_update'),
    url(r'^map/(?P<map_id>[\d]+)/datalayer/delete/(?P<pk>\d+)/$',
        ls_views.DataLayerDelete.as_view(), name='datalayer_delete'),
]

urlpatterns += [

    # Deployments
    url(
        r'^deployment/$',
        RedirectView.as_view(url=reverse_lazy('geomap:deployment_list')),
        name='deployment_index'
    ),
    url(
        r'^deployment/list/$',
        deployment_views.view_deployment_list,
        name='deployment_list'
    ),
    url(
        r'^deployment/detail/(?P<pk>\d+)/$',
        deployment_views.view_deployment_detail,
        name='deployment_detail'
    ),
    url(
        r'^deployment/delete/(?P<pk>\d+)/$',
        deployment_views.view_deployment_delete,
        name='deployment_delete'
    ),
    url(
        r'^deployment/delete/$',
        deployment_views.view_deployment_delete,
        name='deployment_delete_multiple'
    ),
    url(
        r'^deployment/create/$',
        deployment_views.view_deployment_create,
        name='deployment_create'
    ),
    url(
        r'^deployment/update/(?P<pk>\d+)/$',
        deployment_views.view_deployment_update,
        name='deployment_update'
    ),
    url(
        r'^deployment/bulk-update/$',
        deployment_views.view_deployment_bulk_update,
        name='deployment_bulk_update'
    ),
    url(
        r'^deployment/bulk-create/$',
        deployment_views.view_deployment_bulk_create,
        name='deployment_bulk_create'
    ),
    url(
        r'deployment/import/$',
        deployment_views.view_deployment_import,
        name='deployment_import'
    ),
]

trapper/apps/messaging/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

from trapper.apps.messaging import views as messaging_views


urlpatterns = [
    url(
        r'^$',
        RedirectView.as_view(url=reverse_lazy('messaging:message_inbox')),
        name='index'
    ),
    url(
        r'message/detail/(?P<hashcode>\w+)/$',
        messaging_views.view_message_detail,
        name='message_detail'
    ),
    url(
        r'message/inbox/$',
        messaging_views.view_message_inbox,
        name='message_inbox'
    ),
    url(
        r'message/outbox/$',
        messaging_views.view_message_outbox,
        name='message_outbox'
    ),
    url(
        r'message/create/$',
        messaging_views.view_message_create,
        name='message_create'
    ),
    url(
        r'collection-request/list/$',
        messaging_views.view_collection_request_list,
        name='collection_request_list'
    ),
    url(
        r'collection-request/resolve/(?P<pk>\d+)/$',
        messaging_views.view_collection_request_resolve,
        name='collection_request_resolve'
    ),
    url(
        r'collection-request/revoke/(?P<pk>\d+)/$',
        messaging_views.view_collection_request_revoke,
        name='collection_request_revoke'
    ),
]

trapper/apps/research/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from rest_framework.routers import DefaultRouter

from trapper.apps.research.views import api as api_views
from trapper.apps.research.views import research as research_views


router = DefaultRouter(trailing_slash=False)
router.register(
    r'research-projects',
    api_views.ResearchProjectViewSet,
    base_name='api-research-project'
)
router.register(
    r'research-project-collections',
    api_views.ResearchProjectCollectionViewSet,
    base_name='api-research-project-collection'
)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(
        r'^$',
        RedirectView.as_view(url=reverse_lazy('research:project_list')),
        name='project_index'
    ),
]

urlpatterns += [

    url(
        r'project/list/$',
        research_views.view_research_project_list,
        name='project_list'
    ),
    url(
        r'project/detail/(?P<pk>\d+)/$',
        research_views.view_research_project_detail,
        name='project_detail'
    ),
    url(
        r'project/create/$',
        research_views.view_research_project_create,
        name='project_create'
    ),
    url(
        r'project/update/(?P<pk>\d+)/$',
        research_views.view_research_project_update,
        name='project_update'
    ),
    url(
        r'project/delete/(?P<pk>\d+)/$',
        research_views.view_research_project_delete,
        name='project_delete'
    ),
    url(
        r'^project/delete/$',
        research_views.view_research_project_delete,
        name='project_delete_multiple'
    ),
    url(
        r'project/collection/add/$',
        research_views.view_research_project_collection_add,
        name='project_collection_add'
    ),
    url(
        r'^project/collection/delete/$',
        research_views.view_research_project_collection_delete,
        name='project_collection_delete_multiple'
    ),
    url(
        r'^project/collection/delete/(?P<pk>\d+)/$',
        research_views.view_research_project_collection_delete,
        name='project_collection_delete'
    ),
]

trapper/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.gis import admin as admin_gis
from django.conf import settings
from django.conf.urls.static import static
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from trapper.apps.accounts.views import accounts as accounts_views

admin.autodiscover()

urlpatterns = [
    # Overrides
    # Overwrite account inactive url provided by django-allauth so user
    # is redirected to homepage instead of templateless inactive user
    url(
        r'^account/inactive/$',
        RedirectView.as_view(url=reverse_lazy('trapper_index')),
        name='account_inactive'
    ),
    # Trapper homepage
    url(
        r'^$',
        accounts_views.view_index,
        name='trapper_index'
    ),
    # Media classification urls
    url(
        r'^media_classification/',
        include(
            'trapper.apps.media_classification.urls',
            namespace='media_classification'
        )
    ),
    # Research urls
    url(
        r'^research/',
        include(
            'trapper.apps.research.urls',
            namespace='research'
        )
    ),
    # Storage urls
    url(
        r'^storage/',
        include(
            'trapper.apps.storage.urls',
            namespace='storage'
        )
    ),
    # Messaging urls
    url(
        r'^messaging/',
        include(
            'trapper.apps.messaging.urls',
            namespace='messaging'
        )
    ),
    # Accounts urls
    url(
        '',
        include('django.contrib.auth.urls')
    ),
    url(
        r'^accounts/',
        include(
            'trapper.apps.accounts.urls',
            namespace='accounts'
        )
    ),
    url(
        r'^account/',
        include('allauth.urls')
    ),
    # GeoMap urls
    url(
        r'^geomap/',
        include(
            'trapper.apps.geomap.urls',
            namespace='geomap'
        )
    ),
    # Comments
    url(
        r'^comments/',
        include(
            'trapper.apps.comments.urls',
            namespace='comments'
        )
    ),
    # Sendfile urls
    url(
        r'^serve/',
        include(
            'trapper.apps.sendfile.urls',
            namespace='sendfile'
        )
    ),
    # Forum
    url(
        r'^forum/',
        include(
            'djangobb_forum.urls',
            namespace='djangobb'
        )
    ),

    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin_gis/', include(admin_gis.site.urls)),
    url(r'', include('leaflet_storage.urls')),
    # REST API Swagger docs
    url(r'^docs/api/', include('rest_framework_swagger.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = urlpatterns + [
        url(
            r'^__debug__/', 
            include(debug_toolbar.urls)
        )
    ] + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    ) + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

trapper/apps/common/models.py
# -*- coding: utf-8 -*-
"""Model definitions or utils that can be used in other parts of project"""

from django.db import models
from django.conf import settings


class BaseAccessMember(models.Model):
    """Abstract model that hold user and created date field, that can
    be used in various applications

    This model adds:

    * `user` - foreign key to :class:`auth.User`
    * `date_created` - :class:`models.DateTimeField` with default value set to
        :func:`datetime.datetime.now`
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    date_created = models.DateTimeField(auto_now_add=True, editable=False)

    class Meta:
        abstract = True

trapper/apps/extra_tables/models.py
# -*- coding: utf-8 -*-

from django.db import models


class Species(models.Model):
    latin_name = models.CharField(max_length=100, blank=False)
    english_name = models.CharField(max_length=100, blank=False)
    family = models.CharField(max_length=100, blank=True)
    genus = models.CharField(max_length=100, blank=True)

    class Meta:
        ordering = ['english_name']

    def __unicode__(self):
        return unicode('%s : %s') % (self.english_name, self.latin_name)

trapper/apps/comments/forms.py
# -*- coding: utf-8 -*-
"""
Form used to create new comment or reply
"""
from __future__ import unicode_literals

from django.forms import widgets

from crispy_forms.layout import Layout, Fieldset

from trapper.apps.common.forms import BaseCrispyModelForm
from trapper.apps.comments.models import UserComment


class UserCommentForm(BaseCrispyModelForm):
    """This form is used within templatetag to be rendered directly in
    template. Thanks to that, there is no need to modify views logic
    to use comments application"""

    def get_layout(self):
        """Define layout for crispy form helper"""
        return Layout(
            Fieldset(
                '',
                'comment',
                'content_type',
                'object_pk',
                'parent'
            ),
        )

    class Meta:
        model = UserComment
        fields = '__all__'
        widgets = {
            'parent': widgets.HiddenInput(),
            'content_type': widgets.HiddenInput(),
            'object_pk': widgets.HiddenInput()
        }

trapper/apps/extra_tables/forms.py
# -*- coding: utf-8 -*-

trapper/apps/messaging/forms.py
# -*- coding: utf-8 -*-
"""Forms related to Messaging application"""
from __future__ import unicode_literals

from django import forms
from django.contrib.auth import get_user_model

from trapper.apps.messaging.models import Message

User = get_user_model()


class MessageForm(forms.ModelForm):
    """Message form that is used for creating messages to other users.
    This form exclude currently logged in user from list of
    recipients.
    Also sending messages to inactive users is not allowed
    """

    class Meta:
        model = Message
        fields = ['subject', 'text', 'user_to']

    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request', None)
        super(MessageForm, self).__init__(*args, **kwargs)
        # exclude inactive users and current user
        user_to_field = self.fields['user_to']
        user_to_field.queryset = User.objects.filter(
            is_active=True
        ).exclude(pk=request.user.pk)
        # select2 classing
        user_to_field.widget.attrs['class'] = 'form-control select2-default'

trapper/templates/actions_select.html
{% load i18n %}
<div class="form-group">
<div class="controls ">
<select name="action" id="id_action" class="select form-control">
    <option value="-1">--------</option>
    {% for action, attrs in actions %}
        <option {% if attrs.class %}class="{{attrs.class}}"{% endif %} value="{{ forloop.counter }}"> {{ action }}</option>
    {% endfor %}
</select>
</div>
</div>
<button class="btn btn-default" type="submit"> Run action</button>
<a href="#" onclick="selectAll()">select all ({{ paginator.count }})</a>
<input type="hidden" value="{{ paginator.count }}" name="all-items-count">
<input id="select-across" type="hidden" value="0" name="select-across">

<script type="text/javascript">
    var selectAll = function() {
	$('#select-across').val(1);
    }
</script>

trapper/templates/index.html
{% load variables_tags %}
{% load common_tags %}

<!doctype html>
<html class="no-js">
  <head>
    <meta charset="utf-8">
    <title>Trapper</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/main.css">
    <script src="{{ STATIC_URL }}js/vendor.js"></script>

    {% block header %}
    {% block scripts_prepend %}
    {% endblock scripts_prepend %}
    <script src="{{ STATIC_URL }}js/utils/alert.js"></script>
    <script src="{{ STATIC_URL }}js/utils/modal.js"></script>
    <script src="{{ STATIC_URL }}js/utils/uploader.js"></script>
    <script src="{{ STATIC_URL }}js/utils/plugins.js"></script>

    <script src="{{ STATIC_URL }}js/apps/dashboard.js"></script>
    <script src="{{ STATIC_URL }}js/apps/classificator.js"></script>
    <script src="{{ STATIC_URL }}js/apps/classification.js"></script>
    <script src="{{ STATIC_URL }}js/apps/collection.js"></script>
    <script src="{{ STATIC_URL }}js/apps/location.js"></script>
    <script src="{{ STATIC_URL }}js/apps/deployment.js"></script>
    <script src="{{ STATIC_URL }}js/apps/message.js"></script>
    <script src="{{ STATIC_URL }}js/apps/research.js"></script>
    <script src="{{ STATIC_URL }}js/apps/resource.js"></script>
    <script src="{{ STATIC_URL }}js/apps/user.js"></script>

    <script src="{{ STATIC_URL }}js/main.js"></script>

    <script src="{{ STATIC_URL }}js/grid/app.js"></script>
    <script src="{{ STATIC_URL }}js/grid/controllers.js"></script>
    <script src="{{ STATIC_URL }}js/grid/directives.js"></script>
    <script src="{{ STATIC_URL }}js/grid/filters.js"></script>
    <script src="{{ STATIC_URL }}js/grid/services.js"></script>
    {% block scripts_append %}
    {% endblock scripts_append %}
    {% endblock header %}
  </head>

  <body data-static-url="{{ STATIC_URL }}" {% if user.is_authenticated %}data-user="{{ user|pretty_username }}"{% endif %} data-app="{% block data_app %}dashboard{% endblock %}" {% block ng_app %}{% endblock ng_app %}>

    {% with user.is_authenticated as is_authenticated %}
    {% block main_menu %}
      {% include 'main_menu.html' %}
    {% endblock main_menu %}

    {% if messages %}
    <div id="alerts" class="alerts-global">
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
        <div>
          {{ message|safe }}
          <button type="button" class="alert-close"></button>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}

    <div class="container">
      {% block content %}
      <!-- {% get_variable namespace='global' name='app-welcome' %} -->
      {% endblock content %}
    </div>
    {% endwith %}

  </body>
</html>

trapper/templates/input.html
<div class="form-group form-required">
  <label for="{{ field.name }}" class="control-label">Name</label>
  <input type="text" class="form-control" id="name">
</div>

trapper/templates/main_menu.html
{% load variables_tags %}

<nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url "trapper_index" %}">Trapper</a>
    </div>
    
    <ul class="nav navbar-nav">

      <li class="dropdown">
        <a href="#">
          <span class="fa fa-info"></span>
          Info
          <span class="fa fa-angle-down"></span>
        </a>
        <ul class="dropdown-menu">
          <li><a href="{% url "djangobb:index" %}">Forum</a></li>
          <li class="divider"></li>
        </ul>
      </li>

      {% if is_authenticated %}
      {% with user.get_profile as user_profile %}
      <li class="dropdown {{ menu_messages }}">
        <a href="{% url 'messaging:index' %}">
          <span class="fa {% if user_profile.has_unread_messages %}text-primary fa-envelope{% else %}fa-envelope-o{% endif %}"></span>
          Messaging
          <span class="fa fa-angle-down"></span>
        </a>
        
        <ul class="dropdown-menu">
          <li><a href="{% url 'messaging:message_inbox' %}">Inbox</a></li>
          <li><a href="{% url 'messaging:message_outbox' %}">Outbox</a></li>
          <li><a href="{% url 'messaging:message_create' %}"><span class="fa fa-pencil"></span> New message</a></li>
          <li class="divider"></li>
          <li><a href="{% url "messaging:collection_request_list" %}">Requested Collections </a></li>
        </ul>
      </li>
      {% endwith %}
      {% endif %}

      {% if is_authenticated %}
      <li class="dropdown {{ menu_storage }}">
        <a href="{% url 'storage:storage_index' %}">
          <span class="fa fa-database"></span>
          Storage
          <span class="fa fa-angle-down"></span>
        </a>
        <ul class="dropdown-menu">
          <li><a href="{% url "storage:resource_list" %}">Resources (available)</a></li>
          <li><a href="{% url "storage:resource_create" %}"><span class="fa fa-plus"></span> Add resource</a></li>
          <li class="divider"></li>
          <li><a href="{% url 'storage:collection_list' %}">Collections (available)</a></li>
          <li><a href="{% url 'storage:collection_ondemand_list' %}">Collections (on demand)</a></li>
          <li><a href="{% url "storage:collection_upload" %}">
              <span class="fa fa-upload"></span> Upload collection</a>
          </li>
        </ul>
      </li>
      {% endif %}
      
      {% if is_authenticated %}

      <li class="dropdown {{ menu_research }}">
        <a href="{% url 'research:project_index' %}">
          <span class="fa fa-flask"></span>
          Research
          <span class="fa fa-angle-down"></span>
        </a>
        
        <ul class="dropdown-menu">
          <li><a href="{% url 'research:project_list' %}">Research project</a></li>
          <li><a href="{% url 'research:project_create' %}"><span class="fa fa-plus"></span> Add research project</a></li>
        </ul>
      </li>
            
      <li class="dropdown {{ menu_media_classification }}">
        <a href="{% url "media_classification:project_index" %}">
          <span class="fa fa-cubes"></span>
          Media classification
          <span class="fa fa-angle-down"></span>
        </a>
        <ul class="dropdown-menu">
          <li><a href="{% url "media_classification:project_list" %}">Classification projects</a></li>
          <li><a href="{% url "media_classification:project_create" %}"><span class="fa fa-plus"></span> Add classification project</a></li>
          <li><a href="{% url "media_classification:classification_import" %}"><span class="fa fa-upload"></span> Import classifications</a></li>
          <li class="divider"></li>
          <li><a href="{% url "media_classification:classificator_list" %}">Classificators</a></li>
          <li><a href="{% url "media_classification:classificator_create" %}"><span class="fa fa-plus"></span> Add classificator</a></li>
        </ul>
      </li>

      {% endif %}

      {% if is_authenticated %}
      <li class="dropdown {{ menu_geomap }}">
        <a href="#">
          <span class="fa fa-globe"></span>
          Map
          <span class="fa fa-angle-down"></span>
        </a>
        <ul class="dropdown-menu">
          <li><a href="{% url 'geomap:map_view' %}?action=full">Show map</a></li>
          <li><a href="{% url 'geomap:map_list' %}">Saved maps</a></li>
          <li class="divider"></li>
          <li><a href="{% url 'geomap:location_list' %}">Locations</a></li>
          <li><a href="{% url "geomap:location_create" %}"><span class="fa fa-plus"></span> Add location</a></li>
          <li><a href="{% url 'geomap:location_import' %}"><span class="fa fa-upload"></span> Import locations</a></li>
          <li class="divider"></li>
          <li><a href="{% url 'geomap:deployment_list' %}">Deployments</a></li>
          <li><a href="{% url "geomap:deployment_create" %}"><span class="fa fa-plus"></span> Add deployment</a></li>
          <li><a href="{% url 'geomap:deployment_import' %}"><span class="fa fa-upload"></span> Import deployments</a></li>
        </ul>
      </li>
      
      {% if user.is_staff %}
      <li><a href="{% url "admin:index" %}"><span class="fa fa-cogs"></span> Admin site</a></li>
      {% endif %}
      
    </ul>
    {% endif %}

    <ul class="nav navbar-nav pull-right">

      {% if is_authenticated %}
      <li class="{{ menu_profile }}"><a href="{% url "accounts:mine_profile" %}"><span class="fa fa-user"></span> {{ user|pretty_username }}</a></li>
      <li><a href="{% url "account_logout" %}"><span class="fa fa-lock"></span> Logout</a></li>
      {% else %}
      <li class="{{ menu_login }}"><a href="{% url "account_login" %}"><span class="fa fa-lock"></span> Login</a></li>
      <li class="{{ menu_signup }}"><a href="{% url "account_signup" %}"><span class="fa fa-cog"></span> Register</a></li>
      {% endif %}
    </ul>
  </div>
</nav>