trapper/apps/accounts/urls.py
# -*- coding: utf-8 -*-
"""
Urls related to users management
"""
from django.conf.urls import url, include

from rest_framework.routers import DefaultRouter

from trapper.apps.accounts.views import api as api_views
from trapper.apps.accounts.views import accounts as accounts_views


router = DefaultRouter(trailing_slash=False)
router.register(
    r'users', api_views.UserViewSet, base_name='api-user'
)

urlpatterns = [

    url(r'^api/', include(router.urls)),
    url(
        r'^profile/$',
        accounts_views.view_mine_profile,
        name='mine_profile'
    ),
    url(
        r'^profile/(?P<username>[\w_\.\+\-]+)/$',
        accounts_views.view_user_profile,
        name='show_profile'
    ),
    url(
        r'^dashboard/$',
        accounts_views.view_dashbord,
        name='dashboard'
    ),
    url(
        r'^celery/cancel/$',
        accounts_views.view_celery_task_cancel,
        name='celery_task_cancel'
    ),
    url(
        r'^data-package/delete/(?P<pk>\d+)/$',
        accounts_views.view_data_package_delete,
        name='data_package_delete'
    ),
    url(
        r'^data-package/(?P<pk>\d+)/$',
        accounts_views.view_data_package_sendfile_media,
        name='data_package_sendfile_media'
    ),
]

trapper/apps/messaging/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

from trapper.apps.messaging import views as messaging_views


urlpatterns = [
    url(
        r'^$',
        RedirectView.as_view(url=reverse_lazy('messaging:message_inbox')),
        name='index'
    ),
    url(
        r'message/detail/(?P<hashcode>\w+)/$',
        messaging_views.view_message_detail,
        name='message_detail'
    ),
    url(
        r'message/inbox/$',
        messaging_views.view_message_inbox,
        name='message_inbox'
    ),
    url(
        r'message/outbox/$',
        messaging_views.view_message_outbox,
        name='message_outbox'
    ),
    url(
        r'message/create/$',
        messaging_views.view_message_create,
        name='message_create'
    ),
    url(
        r'collection-request/list/$',
        messaging_views.view_collection_request_list,
        name='collection_request_list'
    ),
    url(
        r'collection-request/resolve/(?P<pk>\d+)/$',
        messaging_views.view_collection_request_resolve,
        name='collection_request_resolve'
    ),
    url(
        r'collection-request/revoke/(?P<pk>\d+)/$',
        messaging_views.view_collection_request_revoke,
        name='collection_request_revoke'
    ),
]

trapper/apps/research/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from rest_framework.routers import DefaultRouter

from trapper.apps.research.views import api as api_views
from trapper.apps.research.views import research as research_views


router = DefaultRouter(trailing_slash=False)
router.register(
    r'research-projects',
    api_views.ResearchProjectViewSet,
    base_name='api-research-project'
)
router.register(
    r'research-project-collections',
    api_views.ResearchProjectCollectionViewSet,
    base_name='api-research-project-collection'
)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(
        r'^$',
        RedirectView.as_view(url=reverse_lazy('research:project_list')),
        name='project_index'
    ),
]

urlpatterns += [

    url(
        r'project/list/$',
        research_views.view_research_project_list,
        name='project_list'
    ),
    url(
        r'project/detail/(?P<pk>\d+)/$',
        research_views.view_research_project_detail,
        name='project_detail'
    ),
    url(
        r'project/create/$',
        research_views.view_research_project_create,
        name='project_create'
    ),
    url(
        r'project/update/(?P<pk>\d+)/$',
        research_views.view_research_project_update,
        name='project_update'
    ),
    url(
        r'project/delete/(?P<pk>\d+)/$',
        research_views.view_research_project_delete,
        name='project_delete'
    ),
    url(
        r'^project/delete/$',
        research_views.view_research_project_delete,
        name='project_delete_multiple'
    ),
    url(
        r'project/collection/add/$',
        research_views.view_research_project_collection_add,
        name='project_collection_add'
    ),
    url(
        r'^project/collection/delete/$',
        research_views.view_research_project_collection_delete,
        name='project_collection_delete_multiple'
    ),
    url(
        r'^project/collection/delete/(?P<pk>\d+)/$',
        research_views.view_research_project_collection_delete,
        name='project_collection_delete'
    ),
]

trapper/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.gis import admin as admin_gis
from django.conf import settings
from django.conf.urls.static import static
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from trapper.apps.accounts.views import accounts as accounts_views

admin.autodiscover()

urlpatterns = [
    # Overrides
    # Overwrite account inactive url provided by django-allauth so user
    # is redirected to homepage instead of templateless inactive user
    url(
        r'^account/inactive/$',
        RedirectView.as_view(url=reverse_lazy('trapper_index')),
        name='account_inactive'
    ),
    # Trapper homepage
    url(
        r'^$',
        accounts_views.view_index,
        name='trapper_index'
    ),
    # Media classification urls
    url(
        r'^media_classification/',
        include(
            'trapper.apps.media_classification.urls',
            namespace='media_classification'
        )
    ),
    # Research urls
    url(
        r'^research/',
        include(
            'trapper.apps.research.urls',
            namespace='research'
        )
    ),
    # Storage urls
    url(
        r'^storage/',
        include(
            'trapper.apps.storage.urls',
            namespace='storage'
        )
    ),
    # Messaging urls
    url(
        r'^messaging/',
        include(
            'trapper.apps.messaging.urls',
            namespace='messaging'
        )
    ),
    # Accounts urls
    url(
        '',
        include('django.contrib.auth.urls')
    ),
    url(
        r'^accounts/',
        include(
            'trapper.apps.accounts.urls',
            namespace='accounts'
        )
    ),
    url(
        r'^account/',
        include('allauth.urls')
    ),
    # GeoMap urls
    url(
        r'^geomap/',
        include(
            'trapper.apps.geomap.urls',
            namespace='geomap'
        )
    ),
    # Comments
    url(
        r'^comments/',
        include(
            'trapper.apps.comments.urls',
            namespace='comments'
        )
    ),
    # Sendfile urls
    url(
        r'^serve/',
        include(
            'trapper.apps.sendfile.urls',
            namespace='sendfile'
        )
    ),
    # Forum
    url(
        r'^forum/',
        include(
            'djangobb_forum.urls',
            namespace='djangobb'
        )
    ),

    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin_gis/', include(admin_gis.site.urls)),
    url(r'', include('leaflet_storage.urls')),
    # REST API Swagger docs
    url(r'^docs/api/', include('rest_framework_swagger.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = urlpatterns + [
        url(
            r'^__debug__/', 
            include(debug_toolbar.urls)
        )
    ] + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    ) + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

trapper/apps/accounts/models.py
# -*- coding: utf-8 -*-
"""
Module contains models related to user profile.
When User instance is created, then UserProfile instance is created by
default.

For registration django-allauth is used, but account is not activated.
Instad of mail is sent to admins, so they can activate account
(activation sends email to user).

"""
from __future__ import unicode_literals

import os

from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from  django.core.files.storage import FileSystemStorage
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from django.core.mail import send_mail
from django.utils.timezone import now

from trapper.apps.common.fields import ResizedImageField, SafeTextField
from trapper.apps.messaging.taxonomies import MessageType
from trapper.apps.common.utils.models import delete_old_file
from trapper.apps.common.fields import SafeTextField
from trapper.apps.accounts.utils import (
    get_pretty_username, create_external_media,
    get_external_data_packages_path
)
from trapper.apps.accounts.taxonomy import PackageType, ExternalStorageSettings


class User(AbstractUser):
    class Meta:
        db_table = 'auth_user'


class UserProfile(models.Model):
    """
    Base profile model used to store additional details like avatar,
    some about me description and institution
    """

    user = models.OneToOneField(User)
    avatar = ResizedImageField(
        upload_to='avatars', blank=True, null=True,
        max_width=80, max_height=80
    )
    about_me = SafeTextField(blank=True, null=True)
    institution = models.CharField(max_length=255, blank=True, null=True)
    system_notifications = models.BooleanField(
        default=True, help_text=(
            'Do you want to receive emails with system notifications?'
        )
    )

    def __unicode__(self):
        """By default printing profile should display pretty version
        of username"""
        return get_pretty_username(user=self.user)

    def get_absolute_url(self):
        """Return absolute url to user profile"""
        return reverse(
            'accounts:show_profile', kwargs={'username': self.user.username}
        )

    @property
    def avatar_url(self):
        """Return user avatar or default one"""
        if self.avatar and hasattr(self.avatar, 'url'):
            return self.avatar.url
        else:
            return '{url}accounts/img/avatar.png'.format(
                url=settings.STATIC_URL
            )

    def has_unread_messages(self):
        """Checks whether user has any unread messages
        (see :class:`trapper.apps.messaging.models.Message`).
        """

        return self.user.received_messages.filter(
            date_received=None
        ).exclude(
            message_type__in=[
                MessageType.COLLECTION_REQUEST,
                MessageType.RESOURCE_REQUEST
            ]
        ).exists()

    def count_unread_messages(self):
        """Returns the number of unread messages.
        (see :class:`trapper.apps.messaging.models.Message`).
        """

        return self.user.received_messages.filter(
            date_received=None
        ).exclude(
            message_type__in=[
                MessageType.COLLECTION_REQUEST,
                MessageType.RESOURCE_REQUEST
            ]
        ).count()

    def count_inbox_messages(self):
        """Returns total number of inbox messages.
        (see :class:`trapper.apps.messaging.models.Message`).
        """

        return self.user.received_messages.exclude(
            message_type=MessageType.COLLECTION_REQUEST
        ).count()

    def awaiting_collection_requests(self):
        """Returns the number of collections requests that has not been
        resolved yet.
        This means that some users asked for access to collection
        """

        return self.user.collection_requests.filter(
            resolved_at__isnull=True
        ).count()

    def awaiting_resource_requests(self):
        """Returns the number of resource requests that has not been
        resolved yet.
        This means that some users asked for access to resources
        """

        return self.user.resource_requests.filter(
            resolved_at__isnull=True
        ).count()

    # def can_rate(self, resource):
    #     return
    #     # return True

    def save(self, **kwargs):
        """Delete changed files before save new instance"""
        delete_old_file(self, 'avatar')
        super(UserProfile, self).save(**kwargs)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """When new user is created - create default profile"""
    if created:
        UserProfile.objects.get_or_create(user=instance)

@receiver(pre_save, sender=User)
def active_notifiction(sender, instance, **kwargs):
    """When a user account becomes active a user is notified by mail"""
    if not settings.EMAIL_NOTIFICATIONS:
        return 1
    try:
        old_instance = User.objects.get(pk=instance.pk)
    except User.DoesNotExist:
        pass
    else:
        if (
            old_instance.is_active is False and instance.is_active is True
        ):
            # Ensure that the external media directory exists
            create_external_media(username=instance.username)

            # send an email notification to a user that account has been activated
            send_mail(
                subject='Your Trapper account has just been activated!',
                message=(
                    'Dear {username},\n\n'
                    'We activated your account. Now you can login to Trapper.\n\n'
                    'Best regards,\n'
                    'Trapper Team'
                ).format(username=instance.username.capitalize()),
                from_email=None,
                recipient_list=[instance.email],
                fail_silently=True
            )


class UserTask(models.Model):
    """
    Helper model to save information about user's celery tasks
    """

    user = models.ForeignKey(User)
    task_id = models.CharField(max_length=765, unique=True)


external_media_location = FileSystemStorage(
    location=settings.EXTERNAL_MEDIA_ROOT,
    base_url=settings.EXTERNAL_MEDIA_URL
)

def user_data_package_upload_to(instance, filename):
    return os.path.join(
        instance.user.username,
        ExternalStorageSettings.DATA_PACKAGES, filename
    )

class UserDataPackage(models.Model):
    """
    """
    user = models.ForeignKey(User)
    package = models.FileField(
        storage=external_media_location,
        upload_to=user_data_package_upload_to
    )
    package_type = models.CharField(
        choices=PackageType.CHOICES, max_length=1, null=True, blank=True
    )
    date_created = models.DateTimeField(null=True, blank=True, default=now)
    description = SafeTextField(
        blank=True, null=True
    )

    def filename(self):
        return os.path.basename(self.package.name)

    def can_delete(self, user):
        return self.user == user

    def delete(self, *args, **kwargs):
        self.package.delete()
        super(UserDataPackage, self).delete(*args, **kwargs)

    def get_download_url(self):
        return reverse(
            'accounts:data_package_sendfile_media',
            kwargs={'pk': self.pk}
        )

    

trapper/apps/accounts/views/api.py
# -*- coding: utf-8 -*-

from django.contrib.auth import get_user_model

from rest_framework import permissions

from trapper.apps.accounts import serializers as accounts_serializers
from trapper.apps.common.views_api import PaginatedReadOnlyModelViewSet

User = get_user_model()


class UserViewSet(PaginatedReadOnlyModelViewSet):
    permission_classes = (permissions.IsAuthenticated, )
    queryset = User.objects.all()
    serializer_class = accounts_serializers.UserSerializer

trapper/apps/accounts/templates/accounts/dashboard_includes/celery.html
<div class="panel-heading">
    <h2 class="panel-title">Celery tasks</h2>
</div>

{% if celery_tasks %}
    <table class="table">
        <thead>
        <tr>
            <th>Name</th>
            <th>Start</th>
            <th>End</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
        </thead>

        <tbody>
        {% for task in celery_tasks %}
            <tr class="{{ task.dashboard_status.css }}">
                <td>{{ task.dashboard_name }}</td>
                <td>{{ task.tstamp|date:"d.m.Y H:s" }}</td>
                <td>{{ task.dashboard_end|date:"d.m.Y H:s" }}</td>
                <td><span class="label label-{{ task.dashboard_status.css }}"><span
                        class="fa {{ task.dashboard_status.icon }}"></span> {{ task.state }}</span></td>
                <td>
                    {% if task.dashboard_status.action_stop %}
                        <a href="{% url 'accounts:celery_task_cancel' %}" class="btn btn-xs btn-default btn-cancel"
                           data-task="{{ task.task_id }}" data-tooltip="tooltip" title="Cancel task"><span
                                class="fa fa-remove"></span></a>
                    {% endif %}

                    {% if task.dashboard_status.action_detail %}
                        <button class="btn btn-xs btn-default btn-log" title="Read log"><span
                                class="fa fa-file-o"></span></button>
                        <div data-title="{{ task.dashboard_status.title }}" data-mode="{{ task.state|lower }}">
                            <label>Result:</label>
                            {% if task.result %}
                                <div>{{ task.result|safe|default:"" }}</div>
                            {% endif %}
                            {% if task.traceback %}
                                <pre>{{ task.traceback|default:"" }}</pre>
                            {% endif %}
                        </div>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% else %}
    <div class="alert alert-warning ng-binding"><span class="fa fa-info"></span> List of tasks is empty.</div>
{% endif %}

<div class="panel-footer">
</div>

trapper/apps/accounts/templates/accounts/dashboard_includes/classification_projects.html
<div class="panel-heading">
  <h2 class="panel-title">Classification projects</h2>
</div>
{% if classification_projects %}

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Role</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
  </thead>
  
  <tbody>
    {% for project in classification_projects %}
    {% url 'media_classification:project_detail' project.pk as project_url %}
    <tr>
      <td>
        <a href="{{ project_url }}">
          {{ project.name }}</a>
      </td>
      <td>
        {% for role in project.get_user_roles %}{{ role }}{% if not forloop.last %},
        {% endif %}{% endfor %}
      </td>
      <td>
        <span class="label label-{{ project.is_finished|yesno:"success,danger" }}"><span class="fa fa-check"></span> {{ project.get_status_display }}</span>
      </td>
      <td>
        <a href="{{ project_url }}" class="btn btn-xs btn-default" data-tooltip="tooltip" title="Details"><span class="fa fa-search"></span></a>
        {% if project.can_update %}
        <a href="{% url 'media_classification:project_update' project.pk %}" class="btn btn-xs btn-default" data-tooltip="tooltip" title="Update"><span class="fa fa-pencil"></span></a>
        {% endif %}
        <a href="{% url 'media_classification:classification_list' pk=project.pk %}" class="btn btn-xs btn-default" data-tooltip="tooltip" title="Classification results"><span class="fa fa-eye"></span></a>
      </td>
    </tr>
        {% endfor %}
  </tbody>
</table>
{% else %}
<div class="alert alert-warning ng-binding"><span class="fa fa-info"></span> You have no classification projects.
</div>
{% endif %}

<div class="panel-footer">
  <a href="{% url 'media_classification:project_index' %}" class="btn btn-default btn-sm">More <span class="fa fa-angle-double-right"></span></a>
</div>

trapper/apps/accounts/templates/accounts/dashboard_includes/data_packages.html
<div class="panel-heading">
    <h2 class="panel-title">Data packages (zip archives)</h2>
</div>
{% if data_packages %}
    <table class="table">
        <thead>
        <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Size</th>
            <th>Created at</th>
            <th>Actions</th>
        </tr>
        </thead>

        <tbody>
        {% for data_package in data_packages %}
            {% url 'accounts:data_package_delete' data_package.pk as data_package_delete_url %}
            <tr>
                <td>{{ data_package.filename|truncatechars:21 }}</td>
                <td>{{ data_package.get_package_type_display }}</td>
                <td>{{data_package.package.size|filesizeformat}}</td>
                <td>{{ data_package.date_created|date:"d.m.Y H:s" }}</td>
                <td>
                    <a href="{{ data_package.get_download_url }}" class="btn btn-xs btn-default" data-tooltip="tooltip"
                       title="Download"><span class="fa fa-download"></span></a>
                    <a href="{{ data_package_delete_url }}" class="btn btn-xs btn-danger btn-delete"
                       data-tooltip="tooltip" title="Delete package"><span class="fa fa-trash-o"></span></a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% else %}
    <div class="alert alert-warning ng-binding"><span class="fa fa-info"></span> You have no data_packages.</div>
{% endif %}

<div class="panel-footer">
</div>

trapper/apps/accounts/templates/accounts/dashboard_includes/messages.html
<div class="panel-heading">
    <h2 class="panel-title">Messages</h2>
</div>
{% if inbox_messages %}
    <table class="table">
        <thead>
        <tr>
            <th>Type</th>
            <th>Subject</th>
            <th>Date</th>
            <th>Sender</th>
        </tr>
        </thead>

        <tbody>
        {% for message in inbox_messages %}
            <tr>
                <td><span class="{% if message.is_request %}fa fa-share-alt{% else %}fa fa-envelope{% endif %}"></span>
                </td>
                <td>
                    <a href="{% url 'messaging:message_detail' hashcode=message.hashcode %}">{{ message.subject|safe }}</a>
                </td>
                <td>{{ message.date_sent|date:"d.m.Y, H:i" }}</td>
                <td><a href="{{ message.user_from.userprofile.get_absolute_url }}">{{ message.user_from.username }}</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% else %}
    <div class="alert alert-warning ng-binding"><span class="fa fa-info"></span> Your message box is empty.</div>
{% endif %}

<div class="panel-footer">
    <a href="{% url 'messaging:message_inbox' %}" class="btn btn-default btn-sm">More <span
            class="fa fa-angle-double-right"></span></a>
</div>

trapper/apps/accounts/templates/accounts/dashboard_includes/research_projects.html
<div class="panel-heading">
    <h2 class="panel-title">Research projects</h2>
</div>


{% if research_projects %}
    <table class="table">
        <thead>
        <tr>
            <th>Name</th>
            <th>Role</th>
            <th>Actions</th>
        </tr>
        </thead>

        <tbody>
        {% for project in research_projects %}
            {% url 'research:project_detail' project.pk as project_url %}
            <tr>
                <td><a href="{{ project_url }}">{{ project.acronym }}</a></td>
                <td>{% for role in project.get_user_roles %}{{ role }}{% if not forloop.last %},
                {% endif %}{% endfor %}</td>
                <td>
                    <a href="{{ project_url }}" class="btn btn-xs btn-default" data-tooltip="tooltip"
                       title="Details"><span class="fa fa-search"></span></a>
                    {% if project.can_update %}
                        <a href="{% url 'research:project_update' project.pk %}" class="btn btn-xs btn-default"
                           data-tooltip="tooltip" title="Update"><span class="fa fa-pencil"></span></a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% else %}
    <div class="alert alert-warning ng-binding"><span class="fa fa-info"></span> You have no research projects.</div>
{% endif %}

<div class="panel-footer">
    <a href="{% url 'research:project_list' %}" class="btn btn-default btn-sm">More <span
            class="fa fa-angle-double-right"></span></a>
</div>